defmodule TainaWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :taina

  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_taina_key",
    signing_salt: "ZtB0BnCx",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve the service worker from the root with no-cache so browsers always
  # re-check it for updates (Plug.Static would attach a long/etag cache). The
  # root path also gives it the "/" scope it needs without an extra header.
  plug :service_worker

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :taina,
    gzip: not code_reloading?,
    only: TainaWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :taina
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TainaWeb.Router

  defp service_worker(%Plug.Conn{method: method, request_path: "/sw.js"} = conn, _opts) when method in ["GET", "HEAD"] do
    # Resolved at runtime: in a release app_dir points at the release path, not
    # the build path a compile-time attribute would have captured.
    path = Application.app_dir(:taina, "priv/static/sw.js")

    conn
    |> Plug.Conn.put_resp_header("content-type", "text/javascript; charset=utf-8")
    |> Plug.Conn.put_resp_header("cache-control", "no-cache")
    |> Plug.Conn.put_resp_header("service-worker-allowed", "/")
    |> Plug.Conn.send_file(200, path)
    |> Plug.Conn.halt()
  end

  defp service_worker(conn, _opts), do: conn
end
